### ISSUE TITLE
Include JRuby invokedynamic results

### ISSUE THREAD

**Issue by headius** [CaDs/ruby_benchmarks#1]
The JRuby numbers would likely be improved if you passed `-Xcompile.invokedynamic` to JRuby. This enables an optimizing JVM feature that improves dynamic calls.

I can run it myself locally of course, but it would be nice if the README reflected those numbers, similar to how they reflect MRI's experimental JIT 😄

**Comment by CaDs** [comment]
Added the results of running the benchmark with `-Xcompile.invokedynamic`
Indeed numbers went up, very nice work!


I do take more runs to get stable results though, so I added that as well as a Note in the README.

Thanks for the suggestion.
